import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the coverage reporter. Its bundled HTML/JS ships its own
    // eslint-disable comments, which lint back at us as unused-directive
    // warnings on every run once coverage has been generated.
    "coverage/**",
  ]),
]);

export default eslintConfig;
