import type { AuthResult, DaySummary, Food, FoodEntry, MealType, User } from "./types";

export class ApiError extends Error {
  constructor(
    message: string,
    readonly status: number,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

export interface ApiClientOptions {
  /** Origin of the Next.js app, e.g. http://localhost:3000. Empty for same-origin web. */
  baseUrl?: string;
  /**
   * Supplies a bearer token. The web app omits this and relies on the
   * session cookie; the mobile app reads one from secure storage.
   */
  getToken?: () => string | null | Promise<string | null>;
}

export interface LogEntryInput {
  foodId?: string;
  name?: string;
  quantity?: number;
  meal: MealType;
  date: string;
  calories?: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  /** From `uploadPhoto()`; attaches a picture of the meal to this entry. */
  photoId?: string | null;
}

export function createApiClient({ baseUrl = "", getToken }: ApiClientOptions = {}) {
  async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers);
    // FormData must set its own Content-Type: the multipart boundary is
    // generated by the runtime, and overriding the header loses it.
    if (init.body && !(init.body instanceof FormData)) {
      headers.set("content-type", "application/json");
    }

    const token = await getToken?.();
    if (token) headers.set("authorization", `Bearer ${token}`);

    const response = await fetch(`${baseUrl}${path}`, {
      ...init,
      headers,
      credentials: "include",
    });

    const payload = await response.json().catch(() => null);
    if (!response.ok) {
      throw new ApiError(payload?.error ?? `Request failed (${response.status})`, response.status);
    }
    return payload as T;
  }

  return {
    signup: (input: { email: string; password: string; name?: string }) =>
      request<AuthResult>("/api/auth/signup", { method: "POST", body: JSON.stringify(input) }),

    login: (input: { email: string; password: string }) =>
      request<AuthResult>("/api/auth/login", { method: "POST", body: JSON.stringify(input) }),

    logout: () => request<{ ok: true }>("/api/auth/logout", { method: "POST" }),

    me: () => request<{ user: User }>("/api/auth/me"),

    updateGoal: (dailyCalorieGoal: number) =>
      request<{ user: User }>("/api/auth/me", {
        method: "PATCH",
        body: JSON.stringify({ dailyCalorieGoal }),
      }),

    /**
     * Search the food library, USDA, and Open Food Facts. With no query,
     * returns the user's most-logged foods. `degraded` names any provider
     * that failed or timed out, so the UI can admit the list is partial.
     */
    searchFoods: (query?: string) =>
      request<{ foods: Food[]; source: "search" | "recent"; degraded: string[] }>(
        `/api/foods${query ? `?q=${encodeURIComponent(query)}` : ""}`,
      ),

    getDay: (date: string) => request<DaySummary>(`/api/entries?date=${encodeURIComponent(date)}`),

    logEntry: (input: LogEntryInput) =>
      request<{ entry: FoodEntry }>("/api/entries", {
        method: "POST",
        body: JSON.stringify(input),
      }),

    deleteEntry: (id: string) =>
      request<{ ok: true }>(`/api/entries/${id}`, { method: "DELETE" }),

    /**
     * Uploads a meal photo and returns its id, to pass to `logEntry`.
     *
     * Takes a ready-made FormData rather than a file, because the two
     * platforms disagree about what a file is: the browser appends a `File`
     * or `Blob`, while React Native appends `{ uri, name, type }`. Building
     * it at the call site keeps that difference out of the shared client.
     *
     * Content-Type is deliberately left unset so the runtime can add the
     * multipart boundary itself.
     */
    uploadPhoto: (form: FormData) =>
      request<{ photoId: string }>("/api/photos", { method: "POST", body: form }),

    /** Absolute URL for an uploaded photo, for an <img> or RN <Image>. */
    photoUrl: (photoId: string) => `${baseUrl}/api/photos/${photoId}`,
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
